
FROM python:3.10-slim AS builder

WORKDIR /usr/src/app

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install --upgrade pip
COPY pyproject.toml .
RUN pip install ".[dev]"


FROM python:3.10-slim

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

COPY src/ /app/src
EXPOSE 8000

CMD ["uvicorn", "crypto_finder.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
