
version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    depends_on:
      - db
    environment:

      - DATABASE_URL=postgresql://user:password@db:5432/crypto_db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crypto_db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
