# Hinglish: Yeh docker-compose ka updated version hai.
# Isme humne ek alag PostgreSQL database service add ki hai.

version: '3.8'

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    depends_on:
      - db
    environment:
      # Isse hamari app ko DB se connect karne ka address pata chalega
      - DATABASE_URL=postgresql://user:password@db:5432/crypto_db

  # Database Service
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crypto_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: